version: '3'

services:
  server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - docker_services

networks:
  docker_services:
    external: true
