version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    ports:
      - 1433:1433
    env_file:
      - .env
    volumes:
      - ./volumes/mssql_data:/var/lib/mssql/data
    networks:
      - docker_services

networks:
  docker_services:
    external: true
