version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch-server
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - .env
    volumes:
      - ./volumes/es_data:/usr/share/elasticsearch/data
    networks:
      - docker_services

  logstash:
    image: logstash:7.17.3
    container_name: logstash-server
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/csv:/usr/share/logstash/csv
    networks:
      - docker_services

  kibana:
    image: kibana:7.17.3
    container_name: kibana-server
    ports:
      - 5601:5601
    networks:
      - docker_services

networks:
  docker_services:
    external: true
