version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    pull_policy: always
    tty: true
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - .:/code
      - ./volumes/ollama:/root/.ollama
    networks:
      - docker_services

  web:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Ollama AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    volumes:
      - ./volumes/web_data:/app/backend/data
    networks:
      - docker_services
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama

networks:
  docker_services:
    external: false
