version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres-server
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
    networks:
      - docker_services

networks:
  docker_services:
    external: true
