version: '3'

services:
  server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - docker_services

  insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - 5540:5540
    networks:
      - docker_services

networks:
  docker_services:
    external: true
